amsa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('django.contrib.auth.urls')), #login
    path('', include('apps.app_dashboard.urls')),
    path('admin/', admin.site.urls),
    path('adm/', include('apps.app_administracion.urls')),
    path('factura/', include('apps.app_factura.urls')),
    path('log/', include('apps.app_autenticacion.urls')),
]

apps/app_factura/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime

class Sucursal(models.Model):
    empresa = models.CharField(max_length=80)
    class Meta:
        verbose_name='Empresa'
        verbose_name_plural='Empresas'
    def __str__(self):
        return self.empresa

class Documento(models.Model):
    docCancel = models.CharField(max_length=120)
    url = models.CharField(max_length=100, null=False, blank=False, default='/')
    class Meta:
        verbose_name='Documento'
        verbose_name_plural='Documentos'
    def __str__(self) -> str:
        return self.docCancel

class Solicitud(models.Model):
    solicitante = models.ForeignKey(User, null=False, blank=False, on_delete=models.PROTECT, default=1)
    sucursal = models.ForeignKey(Sucursal, null=False, blank=False,  on_delete=models.PROTECT)
    nombre_cliente = models.CharField(max_length=120, default=None, null=False, blank=False)
    cartera_cliente = models.CharField(max_length=8, default=None, null=False, blank=False)
    folio = models.PositiveSmallIntegerField(null=True, blank=True)
    rfc = models.CharField(max_length=14,null=False)
    UUID = models.CharField(max_length=36, null=False, blank=False)
    motivo_de_cancelacion = models.CharField(max_length=60, null=False)
    fecha_sol_de_cancelacion = models.DateField(null=False, blank=False, default=datetime.datetime.now)
    #fecha_sol_de_cancelacion = models.DateField(null=False, blank=False, default=timezone.now)
    class Meta:
        verbose_name='Solicitud'
        verbose_name_plural='Solicitudes'
    def __str__(self):  
        return str(self.folio)

class NotaCargo(Solicitud):
    documento = models.CharField(max_length=30,  null=False, blank=False, default='Nota de cargo')
    cuenta_contable = models.CharField(max_length=12, null=True, blank=False)
    archivo = models.FileField( upload_to='media/nota_cargo/%d-%m-%Y', max_length=120, null=False, blank=False)
    obs = models.CharField(max_length=600,  null=False, blank=False, default='')
    class Meta:
        verbose_name='Solicitud de nota de cargo'
        verbose_name_plural='Solicitudes de nota de cargo'
    def __str__(self):
        return str(f'Folio: {self.folio}')

class Vehiculo(Solicitud):
    documento = models.CharField(max_length=30,  null=False, blank=False, default='Factura de vehiculo nuevo')
    inv = models.PositiveSmallIntegerField(null=False, blank=False)
    suplementaria = models.BooleanField(null=False, blank=False)
    archivo = models.FileField( upload_to='media/vehiculo/nuevo/%d-%m-%Y', max_length=130, null=False, blank=False)
    obs = models.CharField(max_length=600,  null=False, blank=False, default=None)
    class Meta:
        verbose_name='Vehiculo nuevo'
        verbose_name_plural='Solicidudes de vehiculos nuevos'
    def __str__(self):
        return str(f'Inventario: {self.inv}')

class Vehiculo_seminuevo(Solicitud):
    documento = models.CharField(max_length=30,  null=False, blank=False, default='Factura de vehiculo seminuevo')
    inv = models.PositiveSmallIntegerField(null=False, blank=False)
    suplementaria = models.BooleanField(null=False, blank=False, default=False)
    archivo = models.FileField( upload_to='media/vehiculo/seminuevo/%d-%m-%Y', max_length=130, null=False, blank=False)
    obs = models.CharField(max_length=600,  null=False, blank=False, default=None)
    class Meta:
        verbose_name='Vehiculo seminuevo'
        verbose_name_plural='Solicidudes de vehiculos seminuevos'
    def __str__(self):
        return str(f'Inventario: {self.inv}')

class Motivo_cancelacion_sat(models.Model):
    clave = models.PositiveIntegerField(null= False, blank=False)
    valor = models.CharField(max_length=120, default=None)
    class Meta:
        verbose_name='Clave'
        verbose_name_plural='Claves'
    def __str__(self):
        return str(self.clave) + ('.- ') +(self.valor)

class Solicitud_atendida(models.Model):
    userCancel = models.ForeignKey(User, null=False,  on_delete=models.PROTECT)
    date = models.DateField(default=timezone.now)
    fecha_de_cancelacion = models.DateField(null=False, blank=False, default=timezone.now)
    estatus = models.CharField(max_length=40)
    comentarios = models.CharField(max_length=120, null=True, default='')
    atendida = models.OneToOneField(Solicitud, null=False,  blank=False, on_delete=models.CASCADE)
    class Meta:
        verbose_name='Solicitud atendida'
        verbose_name_plural='Atendidas'
    def __str__(self):
        return str(self.id)

templates/factura/aten.html
{% extends 'base/base.html' %}

{% load static %}
{% block st %}

<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/form.css' %}" rel="stylesheet">

{% endblock %}

<title>{% block title %} AMSA | Atender solicitud {% endblock %}</title>

{% block contect %}

<body>

    <div class="container">
        <main class="form-group">
            <h1 class="h3 mb-3 fw-normal text-center " style="margin-top: 2.5rem;">Atender cancelación</h1>
            <form method="post">
                {% csrf_token %}

                <tr>
                    <th><label for="id_atendida">&nbsp;</label></th>
                    <td><input type="hidden" name="atendida" class="form-control" required id="id_atendida"
                            value="{{ atendida_rq }}"></td>
                </tr>

                <tr>
                    <th><label for="id_fecha_de_cancelacion">Fecha de cancelación:</label></th>
                    <td><input type="text" name="fecha_de_cancelacion" placeholder="DD/MM/AAAA" class="form-control"
                            id="id_fecha_de_cancelacion"><input type="hidden" name="initial-fecha_de_cancelacion"
                            id="initial-id_fecha_de_cancelacion"></td>
                </tr>
                <tr>
                    <th><label for="id_estatus">Estatus:</label></th>
                    <td><input type="text" name="estatus" class="form-control disabled" maxlength="40" required
                            id="id_estatus"></td>
                </tr>

                <tr>
                    <th><label for="id_comentarios">Comentarios:</label></th>
                    <td><textarea name="comentarios" cols="40" rows="10" class="form-control" maxlength="150" required
                            id="id_comentarios" placeholder="Máximo de 150 caracteres">
            </textarea></td>
                </tr>
                <button class="button-person button-right" type="submit">Enviar</button>
            </form>
        </main>
    </div>

</body>

{% endblock %}

templates/factura/editar_sol_atendida.html
{% extends 'base/base.html' %}

{% load static %}

{% block st %}
{% load crispy_forms_tags %}
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/form.css' %}" rel="stylesheet">

{% endblock %}

<title>{% block title %} AMSA | Editar solicitud  {% endblock %}</title>

{% block contect %}

<body>

    <div class="container">
        <main class="form-group">
            <h4 class="h3 mb-3 fw-normal text-center " style="margin-top: 2.5rem;">Edición del formulario</h1>

                <form method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button class="button-person button-right" type="submit">Guardar</button>
                </form>
        </main>
    </div>

</body>

{% endblock %}

templates/factura/form_fac.html
{% extends 'base/base.html' %}

{% load static %}

{% block st %}

<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/form.css' %}" rel="stylesheet">

{% endblock %}

<title>{% block title %} AMSA | Nueva solicitud {% endblock %}</title>



{% block contect %}

<body>
    <div class="conteiner">
        <h4 style="text-align: center; padding-top: 1.5rem;">Solicitud para cancelación de CFDI</h4>
        <main class="form-group">


            <form method="post">
                {% csrf_token %}

                {{ form }}

                <button class="w-100 btn btn-lg btn-primary" type="submit">Enviar solicitud</button>

            </form>

        </main>
    </div>

</body>
{% endblock %}

{% block footer %}

{% endblock %}


{% load static %}
{% block st_js %}

{% endblock %}

templates/factura/formulario_ncargo.html
{% extends 'base/base.html' %}

{% load static %}

{% block st %}

<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/form.css' %}" rel="stylesheet">

{% endblock %}

<title>{% block title %} AMSA | Nueva solicitud {% endblock %}</title>



{% block contect %}

<body>
    <div class="conteiner">
        <h4 style="text-align: center; padding-top: 2.5rem;">Solicitud para cancelación de Nota de cargo</h4>
        <main class="form-group">


            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}

                {{ form }}

                <button class="w-100 btn btn-lg btn-primary" type="submit">Enviar solicitud</button>

                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
                {% endif %}
                <br>
                <br>

            </form>

        </main>
    </div>

</body>
{% endblock %}

{% block footer %}

{% endblock %}


{% load static %}
{% block st_js %}

{% endblock %}

templates/factura/formulario_vehiculo.html
{% extends 'base/base.html' %}

{% load static %}

{% block st %}

<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/form.css' %}" rel="stylesheet">

{% endblock %}

<title>{% block title %} AMSA | Nueva solicitud {% endblock %}</title>



{% block contect %}

<body>
    <div class="conteiner">
        <h4 style="text-align: center; padding-top: 2.5rem;">Solicitud para cancelación vehículo nuevo</h4>
        <main class="form-group">

            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}

                {{ form }}

                <button class="w-100 btn btn-lg btn-primary" type="submit">Enviar solicitud</button>
            </form>

        </main>
    </div>

</body>

{% endblock %}

{% block footer %}

{% endblock %}


{% load static %}
{% block st_js %}

{% endblock %}

templates/factura/formulario_vehiculo_seminuevo.html
{% extends 'base/base.html' %}

{% load static %}

{% block st %}

<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/form.css' %}" rel="stylesheet">

{% endblock %}

<title>{% block title %} AMSA | Nueva solicitud {% endblock %}</title>



{% block contect %}

<body>
    <div class="conteiner">
        <h4 style="text-align: center; padding-top: 2.5rem;">Solicitud para cancelación vehículo seminuevo</h4>
        <main class="form-group">

            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}

                {{ form }}

                <button class="w-100 btn btn-lg btn-primary" type="submit">Enviar solicitud</button>
            </form>

        </main>
    </div>

</body>
{% endblock %}

{% block footer %}

{% endblock %}


{% load static %}
{% block st_js %}

{% endblock %}

templates/factura/index.html
{% extends 'base/base.html' %}


<title>{% block title %}AMSA | Lista {% endblock %}</title>
{% load static %}

{% block st %}
<!--
<script>
    $(document).ready(function () {
        var refreshId = setInterval(function () {
            $('#alerta_incidencias').load('/act');//actualizas el div
        }, 1000);
    });
</script>
-->
{% endblock %}

{% block contect %}

{% if q %}
<table class="table table-hover" style="font-size: .90rem;">
    <thead>
        <tr>
            <th scope="col">Solicitó</th>
            <th scope="col">Documento</th>
            <th scope="col">Folio CFDI</th>
            <th scope="col">RFC cliente</th>
            <th scope="col">UUID</th>
            <th scope="col">Fecha de solicitud</th>
            <th scope="col">Boton</th>
        </tr>
    </thead>
    <tbody>
        {% for x in q %}
        {% for sol in x %}
        <tr>
            <!--<td>{{ sol.solicitudes.solicitante }}</td>-->
            <td>{{ sol.solicitante }}</td>
            <td>{{ sol.documento }}</td>
            <td>{{ sol.folio }}</td>
            <td>{{ sol.rfc }}</td>
            <td>{{ sol.UUID }}</td>
            <td>{{ sol.fecha_sol_de_cancelacion}}</td>
            <td>
                <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal"
                    data-bs-target="#Modal{{ sol.id }}">
                    Detalles
                </button>

                <!-- Modal -->
                <div class="modal fade" id="Modal{{ sol.id }}">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">ID del la solicitud: {{ sol.id }}</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <span class="text-muted font-13">Nombre del cliente</span><br>{{ sol.nombre_cliente }}<br>
                                <hr class="featurette-divider">
                                <span class="text-muted font-13">Motivo de cancelación</span><br>{{ sol.motivo_de_cancelacion }}<br>
                                <hr class="featurette-divider">
                                <span class="text-muted font-13">UUID</span><br>{{ sol.UUID }}<br>
                                <hr class="featurette-divider">
                                <span class="text-muted font-13">Archivo</span><br><a href="#">{{ sol.archivo }}</a><br>

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>

                                {% if user.is_superuser %}
                                <form action="{% url 'form_aten' %}" method="GET">
                                    <input type="hidden" id="id_sol" name="id_sol" value="{{ sol.id }}">
                                    <input type="submit" value="Atender" class="btn btn-outline-success">
                                </form>

                                {% else %}
                                <form action="{% url 'sol_atendida' %}" method="GET">
                                    <input type="hidden" id="id_sol" name="id_sol" value="{{ sol.id }}">
                                    <input type="submit" value="Estatus" class="btn btn-outline-success">
                                </form>
                                {% endif %}

                            </div>
                        </div>
                    </div>
                </div>

            </td>

        </tr>
        {% endfor %}
        {% endfor %}
    </tbody>

</table>

{% else %}
{% if user.is_superuser %}
<br>
<br>
<h2 style="text-align: center;">No hay nada que atender</h2>
<br>
{% else %}
<br>
<br>
<h2 style="text-align: center;">No hay registos de solicitudes con usuario: {{ user.first_name }} {{user.last_name}}
</h2>
{% endif %}
{% endif %}

{% endblock %}

{% block footer %}

{% endblock %}

{% block st_js %}

{% endblock %}

templates/factura/index_real.html
{% extends 'base/base.html' %}


<title>{% block title %}AMSA | Lista {% endblock %}</title>
{% load static %}

{% block st %}
<!--
<script>
    $(document).ready(function () {
        var refreshId = setInterval(function () {
            $('#alerta_incidencias').load('/act');//actualizas el div
        }, 1000);
    });
</script>
-->
{% endblock %}

{% block contect %}

    {% if solicitudes %}
    <table class="table table-hover" style="font-size: .75rem;">
        <thead>
            <tr>
                <th scope="col">Solicito</th>
                <th scope="col">Empresa</th>
                <th scope="col">Documento</th>
                <th scope="col">Cliente</th>
                <th scope="col">Cartera</th>
                <th scope="col">Orden</th>
                <th scope="col">Folio</th>
                <th scope="col">RFC</th>
                <th scope="col"> Motivo de cancelacion</th>
                <th scope="col">Fecha de solicitud</th>
                <th scope="col">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            {% for sol in solicitudes %}
            <tr>
                <td>{{ sol.solicito }}</td>
                <td>{{ sol.sucursal.empresa }}</td>
                <td>{{ sol.documento }}</td>
                <td>{{ sol.nombre_cliente }}</td>
                <td>{{ sol.cartera_cliente }}</td>
                <td>{{ sol.numOrden }}</td>
                <td>{{ sol.folio }}</td>
                <td>{{ sol.rfc }}</td>
                <td>{{ sol.motivo_de_cancelacion }}</td>
                <td>{{ sol.fecha_sol_de_cancelacion}}</td>

                {% if user.is_superuser %}
                 
                <td>
                    
                    <form action="{% url 'form_aten' %}" method="GET">
                        <input type="hidden" id="id_sol" name="id_sol" value="{{ sol.id }}">
                        <input type="submit" value="Atender" class="btn btn-outline-success">
                    </form>
                </td>
                
                {% else %}
                <td>

                    <form action="{% url 'sol_atendida' %}" method="GET">
                        <input type="hidden" id="id_sol" name="id_sol" value="{{ sol.id }}">
                        <input type="submit" value="Estatus" class="btn btn-outline-success">
                    </form>
                </td>
                {% endif %}
            
            </tr>
            {% endfor %}    
        </tbody>
        
    </table>

{% else %}
{% if user.is_superuser %}
<br>
<br>
<h2 style="text-align: center;" >No hay nada que atender</h2>
<br>
{% else %}
<br>
<br>
<h2 style="text-align: center;" >No hay registos de solicitudes con usuario: {{ user.first_name }} {{user.last_name}}</h2>
{% endif %}
{% endif %}



{% endblock %}

{% block footer %}

{% endblock %}

{% block st_js %}

{% endblock %}

templates/factura/sol_atendida.html
{% extends 'base/base.html' %}


<title>{% block title %}AMSA | solicitudes{% endblock %}</title>
{% load static %}

{% block st %}
<link href="{% static 'css/loader.css' %}" rel="stylesheet">
{% endblock %}

{% block contect %}

{% if solicitudes_atendidas %}
<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">Cancelo</th>
            <th scope="col">Fecha de cancelacion</th>
            <th scope="col">Estatus</th>
            <th scope="col">Comentarios</th>
            <th scope="col">Documento</th>
            <th scope="col">Opciones</td>
        </tr>
    </thead>
    <tbody>

        {% for sol in solicitudes_atendidas %}
        <tr>
            <td style="padding-top: .5rem;">{{ sol.userCancel }}</td>
            <td style="padding-top: .5rem;">{{ sol.fecha_de_cancelacion }}</td>
            <td style="padding-top: .5rem;">{{ sol.estatus }}</td>
            <td style="padding-top: .5rem;">{{ sol.comentarios }}</td>
            <td style="padding-top: .5rem;">{{ sol.atendida.documento }}</td>
            {%if user.is_superuser %}

            <td>
                <a class="btn btn-outline-secondary" style="margin-left: .8rem;"
                    href="{% url 'editar_solicitud_atendida' %}">Editar</a>

                <a class="btn btn-outline-danger" style="margin-left: .8rem;"
                    href="{% url 'eliminar_solicitud_atendida' sol.id %}">Eliminar</a>

            </td>
            {% else %}
            <td>
                <a class="btn btn-outline-secondary" href="{% url 'index'%}">Regresar</a>
            </td>
            {% endif %}

        </tr>
    </tbody>
    {% endfor %}
</table>

{% else %}
<br>
<br>
<div id="contenedor_loader">
    <h2 style="text-align: center;">Solicitud en proceso.</h2>
    <div class="loader" id="loader">Loading...</div>
</div>

{% endif %}



{% endblock %}

{% block footer %}

{% endblock %}


{% block st_js %}

{% endblock %}

templates/factura/sol_deleta.html
{% extends 'base/base.html' %}

{% load static %}

{% block st %}

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/form.css' %}" rel="stylesheet">

{% endblock %}

<title>{% block title %} AMSA | Eliminar Atención {% endblock %}</title>



{% block contect %}

<body>
    <div class="conteiner">
        <h4 style="text-align: center; padding-top: 1.5rem;">Elimniar id: </h4>
        <main class="form-group">


            <form method="post">
                {% csrf_token %}

                <button class="btn btn-danger" type="submit">Elimniar</button>
                <button><a class="btn btn-default" href="{% url 'index' %}">Cancelar</a>

            </form>

        </main>
    </div>

</body>
{% endblock %}

{% block footer %}

{% endblock %}


{% load static %}
{% block st_js %}

{% endblock %}

templates/factura/solicitud_filtro.html
{% extends 'base/base.html' %}


<title>{% block title %}AMSA | Solicitudes{% endblock %}</title>
{% load static %}

{% block st %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/index.css' %}" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

{% endblock %}

{% block contect %}

<!--   Body   -->

{% if solicitudes %}
<table class="table table-hover" style="font-size: .75rem;">
    <thead>
        <tr>
            <th scope="col">Solicitó</th>
            <th scope="col">Documento</th>
            <th scope="col">Folio CFDI</th>
            <th scope="col">RFC cliente</th>
            <th scope="col">UUID</th>
            <th scope="col">Fecha de solicitud</th>
            <th scope="col">Boton</th>
        </tr>
    </thead>
    <tbody>
        {% for sol in solicitudes %}
        <tr>
            <td>{{ sol.solicitante }}</td>
            <td>{{ sol.documento }}</td>
            <td>{{ sol.folio }}</td>
            <td>{{ sol.rfc }}</td>
            <td>{{ sol.UUID }}</td>
            <td>{{ sol.fecha_sol_de_cancelacion}}</td>
            <td>
                <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal"
                    data-bs-target="#Modal{{ sol.id }}">
                    Detalles
                </button>

                <!-- Modal -->
                <div class="modal fade" id="Modal{{ sol.id }}">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">ID del la solicitud: {{ sol.id }}</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <span class="text-muted font-13">Nombre del cliente</span><br>{{ sol.nombre_cliente }}<br>
                                <hr class="featurette-divider">
                                <span class="text-muted font-13">Motivo de cancelación</span><br>{{ sol.motivo_de_cancelacion }}<br>
                                <hr class="featurette-divider">
                                <span class="text-muted font-13">UUID</span><br>{{ sol.UUID }}<br>

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>

                                {% if user.is_superuser %}
                                <form action="{% url 'form_aten' %}" method="GET">
                                    <input type="hidden" id="id_sol" name="id_sol" value="{{ sol.id }}">
                                    <input type="submit" value="Atender" class="btn btn-outline-success">
                                </form>

                                {% else %}
                                <form action="{% url 'sol_atendida' %}" method="GET">
                                    <input type="hidden" id="id_sol" name="id_sol" value="{{ sol.id }}">
                                    <input type="submit" value="Estatus" class="btn btn-outline-success">
                                </form>
                                {% endif %}

                            </div>
                        </div>
                    </div>
                </div>

            </td>

        </tr>
        {% endfor %}    
    </tbody>
    
</table>

{% else %}
{% if user.is_superuser %}
<br>
<br>
<h2 style="text-align: center;" >No existe solicitud con folio: {{ folio }} En ningun usuario</h2>
<br>
{% else %}
<br>
<br>
<h2 style="text-align: center;" >No se encuantra el folio <span style="color: red;"> {{ folio }} </span> en el usuario {{ user.first_name }} {{ user.last_name }} </h2>
{% endif %}
{% endif %}




<!-- End body  -->

{% endblock %}

{% block footer %}

{% endblock %}


{% block st_js %}

{% endblock %}

templates/factura/solicitudesmenu.html
{% extends 'base/base.html' %}

{% load static %}
{% block st %}

<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/solicitudesmenu.css' %}" rel="stylesheet">

{% endblock %}

<title>{% block title %} AMSA | Atender solicitud {% endblock %}</title>

{% block contect %}

<body>
    <br>
    <h2 style="text-align: center;">Selecciona el documento a cancelar</h2>
    <div class="contenedor_documentos">

        {% for doc in documento %}
        <a href="{{ doc.url }}">
            <p>{{ doc.docCancel }}</p>
        </a>
        {% endfor %}

    </div>
</body>

{% endblock %}